apiVersion: apps/v1
kind: Deployment

metadata:
  name: recollect-backend
  labels:
    app: recollect-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: recollect-backend

  template:
    metadata:
      labels:
        app: recollect-backend

    spec:
      containers:
        - name: recollect-backend

          image: northamerica-northeast1-docker.pkg.dev/project-ba5e8e78-81ed-459a-856/recollect-backend/recollect-backend:IMAGE_TAG
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 5000

          envFrom:
            - secretRef:
                name: recollect-backend-secrets

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
