apiVersion: v1
kind: Service
metadata:
  name: recollect-backend
  labels:
    app: recollect-backend
spec:
  type: LoadBalancer
  selector:
    app: recollect-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
